import { Prompt } from 'next/font/google';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import NavigationBar from './components/NavigationBar';
import './globals.css';
import { Providers } from './providers';

const prompt = Prompt({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  const supabase = createServerComponentClient({ cookies })

  const {
    data: { session },
  } = await supabase.auth.getSession()
  // console.log("🚀 ~ file: NavigationBar.jsx:13 ~ NavigationBar ~ session:", session)

  return (
    <html lang="en">
      <body className={prompt.className}>
        <Providers>
          <NavigationBar session={session} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
