import { Prompt } from 'next/font/google'
import NavigationBar from './components/NavigationBar'
import './globals.css'
import { Providers } from './providers'

const prompt = Prompt({ subsets: ['latin'], weight: ['400'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={prompt.className}>
        <Providers>
          <NavigationBar />
          {children}
        </Providers>
      </body>
    </html>
  )
}
